export const CMS_BASE_KNOWLEDGE = [
  "CMS Builder Knowledge Base",
  "",
  "Data model:",
  "- Node types: section, row, column, text, image, button, card, badge, avatar, alert, separator, preview (sink only).",
  "- Edge direction: child -> parent. To render in builder preview, connect a root to target id 'preview'.",
  "- Node.id must be unique. ReactFlow node.type should be 'component' for all content nodes; exported schemas can use { rfType: 'component' }.",
  "- CompNodeData: { type, label, props } where 'type' is one of the component types above.",
  "",
  "Ordering & layout:",
  "- Children order is determined by ascending position.x of child nodes under the same parent.",
  "- Common layout patterns: section > column > content, or section > row > (columns/cards).",
  "- section props: background, padding, maxWidth, align(left|center|right).",
  "- row/column props: gap, padding, justify(start|center|between|end), align(start|center|end).",
  "",
  "Content components:",
  "- text props: tag(h1..h6|p), content, fontSize, color, weight, align.",
  "- image props: src, alt, width, height, rounded.",
  "- button props: label, href, size(sm|md|lg), rounded.",
  "- card props: title, description, padding.",
  "- badge props: text, variant(default|secondary|destructive|outline).",
  "- avatar props: src, alt, size, rounded.",
  "- alert props: variant(info|success|warning|destructive), title, description.",
  "- separator props: orientation(horizontal|vertical), thickness, color.",
  "- All components support className and styleJson(JSON string) for custom styling.",
  "",
  "Builder rules:",
  "- Always ensure at least one root connects to node id 'preview' to visualize.",
  "- Use concise sensible defaults; avoid excessive nodes.",
  "- Prefer semantic grouping: column for vertical stacks, row for horizontal groups.",
  "",
  "Patterns:",
  "- Hero: section(center) > column(center) > text(h1) + text(p) + button",
  "- Features(3): section > column > row > (card × 3)",
  "- Pricing(3): section > row(center) > (card × 3) with title/description",
  "- Testimonial: section > column > card > text + avatar + text",
].join("\n")
